#!/bin/sh

PERMS_OWNER=root
PERMS_GROUP=admin
CHOWN=$PERMS_OWNER:$PERMS_GROUP

# set up worktipsnet data dir
[ -e /var/lib/worktipsnet/ ] || mkdir /var/lib/worktipsnet 
chown $CHOWN /var/lib/worktipsnet
chmod g+w /var/lib/worktipsnet

# mv files copied into $INSTALL_PREFIX/extra/ to their proper locations
mv /opt/worktipsnet/extra/worktipsnet_macos_daemon_script.sh /var/lib/worktipsnet
chown $CHOWN /var/lib/worktipsnet/worktipsnet_macos_daemon_script.sh
chmod 770 /var/lib/worktipsnet/worktipsnet_macos_daemon_script.sh

mv /opt/worktipsnet/extra/network.worktips.worktipsnet.daemon.plist /Library/LaunchDaemons/
chown $CHOWN /Library/LaunchDaemons/network.worktips.worktipsnet.daemon.plist
chmod 640 /Library/LaunchDaemons/network.worktips.worktipsnet.daemon.plist

# clean up by removing 'extra/' (so long as it's empty)
rmdir /opt/worktipsnet/extra/

# bootstrap
/opt/worktipsnet/bin/worktipsnet-bootstrap mainnet /var/lib/worktipsnet/bootstrap.signed
chown $CHOWN /var/lib/worktipsnet/bootstrap.signed

# generate configs
/opt/worktipsnet/bin/worktipsnet -g /var/lib/worktipsnet/worktipsnet.ini
chown $CHOWN /var/lib/worktipsnet/worktipsnet.ini

# register with launchd and start
launchctl load /Library/LaunchDaemons/network.worktips.worktipsnet.daemon.plist
launchctl start network.worktips.worktipsnet.daemon
